# -*- coding: utf-8 -*-
"""Data Cleaning( Name Changing and jpg verification)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Igonazio/Sick-Pig-Classifier/blob/main/Dataset%20and%20Data%20cleaning/Data_Cleaning(_Name_Changing_and_jpg_verification).ipynb
"""



import os
import pandas as pd
from torchvision.io import read_image

# Browse all files in a folder
# Programmatically rename the files according to PyTorch's convention

# File naming convention:
# healthy1.jpg
# healthy2.png
# ...
# healthy100.jpg
# sick101.jpg
# sick102.png
# ...

# Note that torchvision's read_image supports only JPEG and PNG formats.

from google.colab import drive
drive.mount('/content/drive')

from os import listdir
from os.path import isfile, join

from os import walk, rename

def rename_data_files(path, prefix, starting_index):
  '''
  Walk through all files in a given path,
  rename them according to the PyTorch convention,
  and then rename the files and also move them to the parent directory.
  '''
  index = starting_index
  for (dirpath, dirnames, filenames) in walk(path):
    for name in filenames:
      _, file_extension = os.path.splitext(name)
      old = join(dirpath, name)
      new = join(os.path.dirname(dirpath), prefix + str(index) + file_extension)
      rename(old, new)
      index += 1
  return index

sick_path = '/content/drive/MyDrive/pig pics cleaned/sick pigs'
current_index = rename_data_files(sick_path, "ill", current_index)

healthy_path = '/content/drive/MyDrive/pig picscleaned/normal pigs'
current_index = rename_data_files(healthy_path, "healthy", 1)



# Check if all images are jpg
from os import walk, rename

def verify_data_files(path):
  '''
  Walk through all files in a given path,
  rename them according to the PyTorch convention,
  and then rename the files and also move them to the parent directory.
  '''
  for (dirpath, dirnames, filenames) in walk(path):
    for name in filenames:
      name_suffix = name[-3:]
      if name_suffix != "jpg":
        print(name)
        prefix, file_extension = os.path.splitext(name)
        old = join(dirpath, name)
        new = join(dirpath, prefix + ".jpg")
        rename(old, new)

cleaned_pig_path="/content/drive/MyDrive/Ai builders/pig pics cleaned"
verify_data_files(cleaned_pig_path)

